package asw.instagnam.ricetteseguite.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import asw.instagnam.api.events.connessioni.ConnessioneCreataEvent;
import lombok.*; 

@Entity 
@Table(uniqueConstraints=@UniqueConstraint(columnNames = {"follower", "followed"}))
@Data @NoArgsConstructor
public class Connessione {

	@Id 
	private Long id; 	//this should not be generated by ricetteseguite; it should instead be passed from connessioni
	
	@Column(nullable=false)
	private String follower; 
	
	@Column(nullable=false)
	private String followed; 
	
	public Connessione(ConnessioneCreataEvent event) {
		this.id = event.getId();
		this.follower = event.getFollower();
		this.followed = event.getFollowed();
	}
	
}
