package asw.instagnam.ricetteseguite.domain;

import javax.persistence.Entity;
import javax.persistence.Id;

import asw.instagnam.api.events.connessioni.ConnessioneCreataEvent;
import lombok.*; 

@Entity 
@Data @NoArgsConstructor
public class Connessione {

	@Id 
	private Long id; 	//this should not be generated by ricetteseguite; it should instead be passed from connessioni
	private String follower; 
	private String followed; 
	
	public Connessione(ConnessioneCreataEvent event) {
		this.id = event.getId();
		this.follower = event.getFollower();
		this.followed = event.getFollowed();
	}
	
}
