package asw.instagnam.ricetteseguite.domain;

import javax.persistence.Entity;
import javax.persistence.Id;

import asw.instagnam.api.events.ricette.RicettaCreataEvent;
import lombok.*; 

@Entity 
@Data @NoArgsConstructor
public class Ricetta {

	@Id 
	private Long id;	//this should not be generated by ricetteseguite; it should instead be passed from ricette
	private String autore; 
	private String titolo; 
	
	public Ricetta(RicettaSeguita rs) {
		this.id = rs.getIdRicetta(); 
		this.autore = rs.getAutoreRicetta(); 
		this.titolo = rs.getTitoloRicetta(); 
	}

	public Ricetta(RicettaCreataEvent event) {
		this.id = event.getId(); 
		this.autore = event.getAutore(); 
		this.titolo = event.getTitolo(); 
	}
	
}
